# Generated by Django 4.2 on 2024-01-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_login', '0002_myuser_user_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_time_online',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
