# Generated by Django 4.2 on 2024-01-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_login', '0003_myuser_last_time_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/%Y%m%d%s/'),
        ),
    ]
