# Generated by Django 4.2 on 2024-01-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_login', '0005_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/7baeb88a-20a0-4032-a7b6-26a8230b7831/'),
        ),
    ]
