# Generated by Django 4.2 on 2024-01-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_login', '0006_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/a85f429a-49bb-47c0-af06-95645d27242f/'),
        ),
    ]
