# Generated by Django 4.2 on 2024-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_login', '0007_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/2f6bc1df-02cb-43af-8c60-2f2be93878c5/'),
        ),
    ]
